function [Dissipation,kin_Sp,kin_Ph,kin_E,up] = ...
                                SpecProp(E,k,nu,...
                                         u,v,w,...
                                         dim,dx)
%     kin_Sp = trapz(k,E);
    kin_Sp = sum(E)*dx;
    Dissipation = sum(2*nu.*k.^2.*E')*dx;
%     Dissipation = trapz(k,2*nu.*k.^2.*E'); 
    up = sqrt(1/3/dim^3*sum(sum(sum(u.^2+v.^2+w.^2))));
    kin_Ph = sum(sum(sum(0.5*(u.^2+v.^2+w.^2))))/length(u)^3;
    kin_E=sum(sum(sum(0.5*(fftn(u).*conj(fftn(u))+...
                           fftn(v).*conj(fftn(v))+...
                           fftn(w).*conj(fftn(w))))...
               /size(u,1)^6));
end